export const MODULE_NAME = "workforce";

export const EMPTY_STRING = "";
export const WORKFORCE_MAIN_MENU_CONTRIBUTION_KEY = "workforce.MainMenu";

export const WORKFORCE_GENDER = [
  {
    name: "workforce.gender.male",
    id: "M",
  },
  {
    name: "workforce.gender.female",
    id: "F",
  },
  {
    name: "workforce.gender.other",
    id: "O",
  },
];

export const WORKFORCE_COMPANY_STATUS = [
  "Draft",
  "Pending",
  "Approve",
];

export const WORKFORCE_STATUS = {
  ACTIVE: "active",
  INACTIVE: "inactive",
  PENDING: "pending",
  DRAFT: "draft",
  INITIAL: "initial",
  SUSPENDED: "suspended",
  TERMINATED: "terminated",
  ON_LEAVE: "on_leave",
  COMPLETED: "completed",
  ARCHIVED: "archived",
  APPROVED_BY_DG: "approved_by_dg",
  APPROVED_BY_DIRECTOR: "approved_by_director",
  APPROVED_BY_DOCTOR: "approved_by_doctor",
  REJECTED: "rejected",
  REJECTED_BY_DG: "rejected_by_dg",
  DEACTIVATED: "deactivated",
  REINSTATED: "reinstated",
  UNDER_REVIEW: "under_review",
  ESCALATED: "escalated",
  WAITING_FOR_INPUT: "waiting_for_input",
  ON_HOLD: "on_hold",
  CANCELED: "canceled",
  EXPIRED: "expired",
  DISABLED: "disabled",
  REASSIGNED: "reassigned",
  RESIGNED: "resigned",
  FORWARD_TO_DG: "forward_to_dg",
  FORWARD_TO_DIRECTOR: "forward_to_director",
  FORWARD_TO_COMIITEE:"forward_to_comiitee",
  SECOND_FORWARD:"second_forward",
  THIRD_FORWARD:"third_forward",
  NEW:"new",
  REVERT_TO_APPLICANT:"revert_to_applicant",
  REVERT_TO_CHECKER:"revert_to_checker",
  REVERT:"revert",
  FORWARD_TO_ASSOCIATION:"forward_to_association",
  FORWARD_TO_CF_SECTION:"forward_to_cf_section",
  FORWARD_FOR_VERIFICATION:"forward_for_verification",
  VERIFIED:"verified",
  FORWARD_TO_CF_SECTION_ONE:"forward_to_cf_section_one",
  FORWARD_TO_CF_SECTION_TWO:"forward_to_cf_section_two",
  FORWARD_TO_DOCTOR:"forward_to_doctor",
  SELECTED: "selected",
  MEETING_CREATED: "meeting_created",

};
export const STATUS_MAP_BN  = {
  active: "সক্রিয়",
  inactive: "নিষ্ক্রিয়",
  pending: "অপেক্ষমাণ",
  draft: "খসড়া",
  initial: "প্রাথমিক",
  suspended: "বহিষ্কৃত",
  terminated: "বাতিল",
  on_leave: "ছুটিতে",
  completed: "সম্পন্ন",
  archived: "আর্কাইভকৃত",
  approved_by_dg: "মহাপরিচালক দ্বারা অনুমোদিত",
  approved_by_director: "পরিচালক দ্বারা অনুমোদিত",
  approved_by_doctor: "ডাক্তার দ্বারা অনুমোদিত",
  rejected: "বাতিলকৃত",
  rejected_by_dg: "ডিজি কর্তৃক বাতিলকৃত",
  deactivated: "নিষ্ক্রিয় করা হয়েছে",
  reinstated: "পুনর্বহাল",
  under_review: "পর্যালোচনায় রয়েছে",
  escalated: "উর্ধ্বে প্রেরিত",
  waiting_for_input: "ইনপুটের জন্য অপেক্ষা",
  on_hold: "স্থগিত",
  canceled: "বাতিল করা হয়েছে",
  expired: "মেয়াদোত্তীর্ণ",
  disabled: "অক্ষম",
  reassigned: "পুনরায় বরাদ্দকৃত",
  resigned: "পদত্যাগ করেছেন",
  forward_to_dg: "মহাপরিচালকের কাছে প্রেরণ",
  forward_to_director: "পরিচালকের কাছে প্রেরণ",
  forward_to_comiitee: "কমিটির কাছে প্রেরণ",
  second_forward: "দ্বিতীয় দফা প্রেরণ",
  third_forward: "তৃতীয় দফা প্রেরণ",
  new: "নতুন",
  revert_to_applicant: "আবেদনকারীর কাছে ফেরত",
  revert_to_checker: "যাচাইকরণকারীর কাছে ফেরত",
  revert: "আবেদন ফেরত পাঠানো হয়েছে",
  forward_to_association: "অ্যাসোসিয়েশনের কাছে প্রেরণ",
  forward_to_cf_section: "সিএফ শাখায় প্রেরণ",
  forward_for_verification: "যাচাইয়ের জন্য প্রেরণ",
  verified: "যাচাইকৃত",
  forward_to_cf_section_one: "সিএফ শাখা-১ এ প্রেরণ",
  forward_to_cf_section_two: "সিএফ শাখা-২ এ প্রেরণ",
  forward_to_doctor: "ডক্টরের কাছে প্রেরণ",
  selected: "নির্বাচিত",
  meeting_created: "সভা তৈরি হয়েছে"

};
export const STATUS_MAP_EN = {
  active: "Active",
  inactive: "Inactive",
  pending: "Pending",
  draft: "Draft",
  initial: "Initial",
  suspended: "Suspended",
  terminated: "Terminated",
  on_leave: "On Leave",
  completed: "Completed",
  archived: "Archived",
  approved_by_dg: "Approved by DG",
  approved_by_director: "Approved by Director",
  approved_by_doctor: "Approved by Doctor",
  rejected: "Rejected",
  rejected_by_dg: "Rejected By DG",
  deactivated: "Deactivated",
  reinstated: "Reinstated",
  under_review: "Under Review",
  escalated: "Escalated",
  waiting_for_input: "Waiting for Input",
  on_hold: "On Hold",
  canceled: "Canceled",
  expired: "Expired",
  disabled: "Disabled",
  reassigned: "Reassigned",
  resigned: "Resigned",
  forward_to_dg: "Forward to DG",
  forward_to_director: "Forward to Director",
  forward_to_comiitee: "Forward to Committee",
  second_forward: "Second Forward",
  third_forward: "Third Forward",
  new: "New",
  revert_to_applicant: "Revert to Applicant",
  revert_to_checker: "Revert to Checker",
  revert: "Application returned",
  forward_to_association: "Forward to Association",
  forward_to_cf_section: "Forward to CF Section",
  forward_to_cf_section_one: "Forward to CF Section-1",
  forward_to_cf_section_two: "Forward to CF Section-2",
  forward_for_verification: "Forward For Verification",
  verified: "Verified",
  forward_to_doctor: "Forward to Doctor",
  selected: "Selected",
  meeting_created: "Meeting Created"
};


export const WORKFORCE_USER_TYPE = {
  ADMIN: "admin",
  CHECKER: "checker",
  CHECKER_TWO: "checker_two",
  APPROVER: "approver",
  BLWF_APPROVER: "blwf_approver",
  APPLICANT: "applicant",
  FACTORY_ADMIN: "factory_admin",
  DIRECTOR: "director",
  BGMEA_ASSOCIATION: "bgmea_association",
  BKMEA_ASSOCIATION: "bkmea_association",
  SECTION_ADMIN: "section_admin",
  SECTION_ADMIN_TWO: "section_admin_two",
  BLWF_SECTION_ADMIN: "blwf_section_admin",
  DOCTOR: "doctor",
  SEC1_DEPUTI_ASST_DIRECTOR: "sec1_deputi_asst_director ",
  SEC2_DEPUTI_ASST_DIRECTOR: "sec2_deputi_asst_director ",
  BLWF_CHECKER: "blwf_checker",
  BLWF_DEPUTI_ASST_DIRECTOR: "blwf_deputi_asst_director",
  BLWF_DIRECTOR: "blwf_director",

};
export const WORKFORCE_USER_TYPE_MAP_EN= {
  admin: "Admin",
  checker: "Checker",
  checker_two: "Checker Two",
  approver: "Approver",
  blwf_approver: "Blwf Approver",
  applicant: "Applicant",
  factory_admin: "Factory Admin",
  director: "Director",
  bgmea_association: "BGMEA Association",
  bkmea_association: "BKMEA Association",
  section_admin: "Section Admin",
  section_admin_two: "Section Admin Two",
  blwf_section_admin: "Blwf Section Admin",
  doctor: "Doctor",
  sec1_deputi_asst_director: "Sec1 Deputi Asst Director",
  sec2_deputi_asst_director: "Sec2 Deputi Asst Director",
  blwf_checker: "BLWF Checker",
  blwf_deputi_asst_director: "BLWF Deputi Asst Director",
  blwf_director: "BLWF Director",
};
export const WORKFORCE_USER_TYPE_MAP_BN = {
  admin: "অ্যাডমিন",
  checker: "চেকার",
  checker_two: "চেকার ২",
  approver: "অনুমোদনকারী",
  blwf_approver: "বিএলডাব্লিউএফ অনুমোদনকারী",
  applicant: "আবেদনকারী",
  factory_admin: "ফ্যাক্টরি অ্যাডমিন",
  director: "পরিচালক",
  bgmea_association: "বিজিএমইএ অ্যাসোসিয়েশন",
  bkmea_association: "বিকেএমইএ অ্যাসোসিয়েশন",
  section_admin: "সেকশন-১ অ্যাডমিন",
  section_admin_two: "সেকশন-২ অ্যাডমিন",
  blwf_section_admin: "বিএলডাব্লিউএফ সেকশন অ্যাডমিন",
  doctor: "ডাক্তার",
  sec1_deputi_asst_director: "শাখা-১ উপ-সহকারী পরিচালক",
  sec2_deputi_asst_director: "শাখা-২ উপ-সহকারী পরিচালক",
  blwf_deputi_asst_director: "বিএলডাব্লিউএফ উপ-সহকারী পরিচালক",
  blwf_director: "বিএলডাব্লিউএফ পরিচালক",

};

export const statusOptions = [
  { value: "active", label: "সক্রিয়" },
  { value: "inactive", label: "নিষ্ক্রিয়" },
  { value: "pending", label: "অপেক্ষমাণ" },
  { value: "draft", label: "খসড়া" },
  { value: "initial", label: "প্রাথমিক" },
  { value: "suspended", label: "বহিষ্কৃত" },
  { value: "terminated", label: "বাতিল" },
  { value: "on_leave", label: "ছুটিতে" },
  { value: "completed", label: "সম্পন্ন" },
  { value: "archived", label: "আর্কাইভকৃত" },
  { value: "approved_by_dg", label: "মহাপরিচালক দ্বারা অনুমোদিত" },
  { value: "approved_by_director", label: "পরিচালক দ্বারা অনুমোদিত" },
  { value: "approved_by_doctor", label: "ডাক্তার দ্বারা অনুমোদিত" },
  { value: "rejected", label: "বাতিলকৃত" },
  { value: "rejected_by_dg", label: "ডিজি কর্তৃক বাতিলকৃত" },
  { value: "deactivated", label: "নিষ্ক্রিয় করা হয়েছে" },
  { value: "reinstated", label: "পুনর্বহাল" },
  { value: "under_review", label: "পর্যালোচনায় রয়েছে" },
  { value: "escalated", label: "উর্ধ্বে প্রেরিত" },
  { value: "waiting_for_input", label: "ইনপুটের জন্য অপেক্ষা" },
  { value: "on_hold", label: "স্থগিত" },
  { value: "canceled", label: "বাতিল করা হয়েছে" },
  { value: "expired", label: "মেয়াদোত্তীর্ণ" },
  { value: "disabled", label: "অক্ষম" },
  { value: "reassigned", label: "পুনরায় বরাদ্দকৃত" },
  { value: "resigned", label: "পদত্যাগ করেছেন" },
  { value: "forward_to_dg", label: "মহাপরিচালকের কাছে প্রেরণ" },
  { value: "forward_to_director", label: "পরিচালকের কাছে প্রেরণ" },
  { value: "forward_to_comiitee", label: "কমিটির কাছে প্রেরণ" },
  { value: "second_forward", label: "দ্বিতীয় দফা প্রেরণ" },
  { value: "third_forward", label: "তৃতীয় দফা প্রেরণ" },
  { value: "new", label: "নতুন" },
  { value: "revert_to_applicant", label: "আবেদনকারীর কাছে ফেরত" },
  { value: "revert_to_checker", label: "যাচাইকরণকারীর কাছে ফেরত" },
  { value: "revert", label: "আবেদন ফেরত পাঠানো হয়েছে" },
  { value: "forward_to_association", label: "অ্যাসোসিয়েশনের কাছে প্রেরণ" },
  { value: "forward_to_cf_section", label: "সিএফ শাখায় প্রেরণ" },
  { value: "forward_to_cf_section_one", label: "সিএফ শাখা-১ এ প্রেরণ" },
  { value: "forward_to_cf_section_two", label: "সিএফ শাখা-২ এ প্রেরণ" },
  { value: "forward_to_doctor", label: "ডক্টরের কাছে প্রেরণ" },
  { value: "selected", label: "নির্বাচিত" },
  { value: "meeting_created", label: "সভা তৈরি হয়েছে" },
];

export const applicationTypeOptions = [
  { value: "medicalAssistance", label: "চিকিৎসা অনুদান" },
  { value: "scholarship", label: "শিক্ষা অনুদান" },
  { value: "financialAssistance", label: "মৃত্যুজনিত অনুদান" },
  { value: "maternityGrant", label: "মাতৃত্বজনিত অনুদান" },
  { value: "disabilityAssistance", label: "স্থায়ী ও আংশিক অক্ষমতা জনিত আর্থিক সহায়তা" },
];

export const submittedByOptions = [
  { value: "applicant", label: "আবেদনকারী" },
  { value: "factory_admin", label: "ফ্যাক্টরি অ্যাডমিন" },
];

export const banglaLabels = {
  // same as your original banglaLabels object...
  nameEn: "নাম (ইংরেজি)",
  nameBn: "নাম (বাংলা)",
  firstNameEn: "নাম (ইংরেজি)",
  firstNameBn: "নাম (বাংলা)",
  fatherNameEn: "পিতার নাম (ইংরেজি)",
  fatherNameBn: "পিতার নাম (বাংলা)",
  motherNameEn: "মাতার নাম (ইংরেজি)",
  motherNameBn: "মাতার নাম (বাংলা)",
  spouseNameEn: "স্বামীর / স্ত্রীর নাম (ইংরেজি)",
  spouseNameBn: "স্বামী/স্ত্রীর নাম (বাংলা)",
  citizenship: "নাগরিকত্ব",
  nid: "এনআইডি",
  birthCertificate: "জন্ম সনদ",
  birthCertificateNo: "জন্ম সনদ নম্বর",
  birthDate: "জন্ম তারিখ",
  insuranceNumber: "ইনসুরেন্স নম্বর",
  gender: "লিঙ্গ",
  maritalStatus: "বৈবাহিক অবস্থা",
  phoneNumber: "ফোন নম্বর",
  email: "ইমেইল",
  lifeStatus: "জীবিত অবস্থা",
  deathDate: "মৃত্যুর তারিখ",
  monthlyEarning: "মাসিক আয়",
  presentAddress: "বর্তমান ঠিকানা",
  permanentAddress: "স্থায়ী ঠিকানা",
  presentLocation: "বর্তমান এলাকা",
  permanentLocation: "স্থায়ী এলাকা",
  accountNumber: "অ্যাকাউন্ট নম্বর",
  accountHolderName: "হোল্ডারের নাম",
  routingNumber: "রাউটিং নম্বর",
  branch: "শাখা",
  cronicDiseaseType: "জটিল রোগের ধরন",
  grantAmount: "অনুদানের পরিমাণ",
  diagnosisDate: "রোগ নির্ণয়ের তারিখ",
  doctorName: "ডাক্তারের নাম",
  admitted: "হাসপাতালে ভর্তি",
  hospitalName: "হাসপাতালের নাম",
  admitDate: "ভর্তির তারিখ",
  releaseDate: "ছাড়পত্রের তারিখ",
  hospitalDoctorName: "হাসপাতালের ডাক্তার",
  accidentType: "দুর্ঘটনার ধরণ",
  accidentPlace: "দুর্ঘটনার স্থান",
  accidentDate: "দুর্ঘটনার তারিখ",
  accidentTime: "দুর্ঘটনার সময়",
  inOutsideFactory: "কারখানার ভিতরে/বাইরে",
  reJoiningDate: "পুনঃযোগদানের তারিখ",
  educationInstituteName: "শিক্ষা প্রতিষ্ঠানের নাম",
  studyingClass: "অধ্যয়নরত শ্রেণী",
  educationLevel: "শিক্ষার স্তর",
  childNameEn: "শিশুর নাম (ইংরেজি)",
  childNameBn: "শিশুর নাম (বাংলা)",
  childBirthDate: "জন্ম তারিখ",
  childBirthCertificateNo: "জন্ম সনদ নম্বর",
  childNidNo: "এনআইডি নম্বর",
  institution: "শিক্ষা প্রতিষ্ঠান",
  studyClass: "শ্রেণি",
  educationBoard: "বোর্ড",
  passingYear: "পাসিং বছর",
  rollNumber: "রোল নম্বর",
  registrationNumber: "রেজিস্ট্রেশন নম্বর",
  result: "ফলাফল",
  otherInfo: "অন্যান্য তথ্য",
  dateofReceipt: "গ্রহণের তারিখ",
  reasonforReceipt: "গ্রহণের কারণ",
  disabilityType: "প্রতিবন্ধিতার ধরণ",
  deathType: "মৃত্যুর ধরণ",
  scholarshipFor: "স্কলারশিপের উদ্দেশ্য",
  employeeDependentInfo: "নির্ভরশীল সদস্যদের তথ্য",
  employeeBankInfo: "শ্রমিকের ব্যাংক তথ্য",
  applicant_type: "আবেদনকারীর ধরণ",
  bankCode: "ব্যাংক কোড",
  bank: "ব্যাংক",
  educations: "শিক্ষাগত তথ্য",
  spouseBn: "স্বামী/স্ত্রীর নাম (বাংলা)",
  spouseEn: "স্বামী/স্ত্রীর নাম (ইংরেজি)",
  spouseFatherNameEn: "স্বামী/স্ত্রীর পিতার নাম (ইংরেজি)",
  spouseFatherNameBn: "স্বামী/স্ত্রীর পিতার নাম (বাংলা)",
  spouseBirthDate: "স্বামী/স্ত্রীর জন্ম তারিখ",
  spouseNid: "স্বামী/স্ত্রীর এনআইডি",
  applicantInfo: "আবেদনকারীর তথ্য",
  workforceEmployee: "শ্রমিকের তথ্য",
  relationWithApplicant: "আবেদনকারীর সাথে সম্পর্ক",
  houseName: "বাড়ির নাম",
  paraMahalla: "পাড়া মহল্লা",
  villageRoad: "গ্রামের রাস্তা",
  extraInfo: "অতিরিক্ত তথ্য",
  postOffice: "ডাকঘর",
  postCode: "পোস্ট কোড",
  nameEn: "নাম (ইংরেজি)",
  nameBn: "নাম (বাংলা)",
  name: "নাম",
  roadName: "রাস্তার নাম",
  apartmentNumber: "অ্যাপার্টমেন্ট নম্বর",
  relationType: "সম্পর্কের ধরণ",
  bankCode: "ব্যাংক কোড",
  routingNumber: "রাউটিং নম্বর",
  districtCode: "জেলা কোড",
  districtNameEn: "জেলার নাম (ইংরেজি)",
  districtNameBn: "জেলার নাম (বাংলা)",
  employeeAccidentInfo: "শ্রমিকের চিকিৎসার তথ্য",
  ApplicationType: "আবেদনের ধরণ",
  OrganizationType: "প্রতিষ্ঠানের ধরণ",
  TrackingNumber: "ট্র্যাকিং নাম্বার",
  Status: "অবস্থা",
  SubmittedBy: "জমা দিয়েছেন",
  GrantAmount: "অনুদানের পরিমাণ",
  CreatedDate: "আবেদনের তারিখ",
  metadata:"অন্যান্য তথ্য",
  employeeChildrenInfo:"শিক্ষাগত তথ্য",
  applicationFor:"আবেদন কার জন্য"
};