export const MODULE_NAME = "workforce";

export const EMPTY_STRING = "";
export const WORKFORCE_MAIN_MENU_CONTRIBUTION_KEY = "workforce.MainMenu";

export const WORKFORCE_GENDER = [
  {
    name: "Male",
    id: "M",
  },
  {
    name: "Female",
    id: "F",
  },
  {
    name: "Other",
    id: "O",
  },
];

export const WORKFORCE_COMPANY_STATUS = [
  "Draft",
  "Pending",
  "Approve",
];

export const WORKFORCE_STATUS = {
  ACTIVE: "active",
  INACTIVE: "inactive",
  PENDING: "pending",
  DRAFT: "draft",
  INITIAL: "initial",
  SUSPENDED: "suspended",
  TERMINATED: "terminated",
  ON_LEAVE: "on_leave",
  COMPLETED: "completed",
  ARCHIVED: "archived",
  APPROVED_BY_DG: "approved_by_dg",
  APPROVED_BY_DIRECTOR: "approved_by_director",
  REJECTED: "rejected",
  DEACTIVATED: "deactivated",
  REINSTATED: "reinstated",
  UNDER_REVIEW: "under_review",
  ESCALATED: "escalated",
  WAITING_FOR_INPUT: "waiting_for_input",
  ON_HOLD: "on_hold",
  CANCELED: "canceled",
  EXPIRED: "expired",
  DISABLED: "disabled",
  REASSIGNED: "reassigned",
  RESIGNED: "resigned",
  FORWARD_TO_DG: "forward_to_dg",
  FORWARD_TO_DIRECTOR: "forward_to_director",
  FORWARD_TO_COMIITEE:"forward_to_comiitee",
  SECOND_FORWARD:"second_forward",
  THIRD_FORWARD:"third_forward",
  NEW:"new",
  REVERT_TO_APPLICANT:"revert_to_applicant",
  REVERT_TO_CHECKER:"revert_to_checker",
  REVERT:"revert",
  FORWARD_TO_ASSOCIATION:"forward_to_association",
  FORWARD_TO_CF_SECTION:"forward_to_cf_section",
  SELECTED: "selected",
  MEETING_CREATED: "meeting_created",

};
export const STATUS_MAP_BN  = {
  active: "সক্রিয়",
  inactive: "নিষ্ক্রিয়",
  pending: "অপেক্ষমাণ",
  draft: "খসড়া",
  initial: "প্রাথমিক",
  suspended: "বহিষ্কৃত",
  terminated: "বাতিল",
  on_leave: "ছুটিতে",
  completed: "সম্পন্ন",
  archived: "আর্কাইভকৃত",
  approved_by_dg: "মহাপরিচালক দ্বারা অনুমোদিত",
  approved_by_director: "পরিচালক দ্বারা অনুমোদিত",
  rejected: "প্রত্যাখ্যাত",
  deactivated: "নিষ্ক্রিয় করা হয়েছে",
  reinstated: "পুনর্বহাল",
  under_review: "পর্যালোচনায় রয়েছে",
  escalated: "উর্ধ্বে প্রেরিত",
  waiting_for_input: "ইনপুটের জন্য অপেক্ষা",
  on_hold: "স্থগিত",
  canceled: "বাতিল করা হয়েছে",
  expired: "মেয়াদোত্তীর্ণ",
  disabled: "অক্ষম",
  reassigned: "পুনরায় বরাদ্দকৃত",
  resigned: "পদত্যাগ করেছেন",
  forward_to_dg: "মহাপরিচালকের কাছে প্রেরণ",
  forward_to_director: "পরিচালকের কাছে প্রেরণ",
  forward_to_comiitee: "কমিটির কাছে প্রেরণ",
  second_forward: "দ্বিতীয় দফা প্রেরণ",
  third_forward: "তৃতীয় দফা প্রেরণ",
  new: "নতুন",
  revert_to_applicant: "আবেদনকারীর কাছে ফেরত",
  revert_to_checker: "যাচাইকরণকারীর কাছে ফেরত",
  revert: "ফেরত",
  forward_to_association: "অ্যাসোসিয়েশনের কাছে প্রেরণ",
  forward_to_cf_section: "সিএফ শাখায় প্রেরণ",
  selected: "নির্বাচিত",
  meeting_created: "সভা তৈরি হয়েছে"

};
export const STATUS_MAP_EN = {
  active: "Active",
  inactive: "Inactive",
  pending: "Pending",
  draft: "Draft",
  initial: "Initial",
  suspended: "Suspended",
  terminated: "Terminated",
  on_leave: "On Leave",
  completed: "Completed",
  archived: "Archived",
  approved_by_dg: "Approved by DG",
  approved_by_director: "Approved by Director",
  rejected: "Rejected",
  deactivated: "Deactivated",
  reinstated: "Reinstated",
  under_review: "Under Review",
  escalated: "Escalated",
  waiting_for_input: "Waiting for Input",
  on_hold: "On Hold",
  canceled: "Canceled",
  expired: "Expired",
  disabled: "Disabled",
  reassigned: "Reassigned",
  resigned: "Resigned",
  forward_to_dg: "Forward to DG",
  forward_to_director: "Forward to Director",
  forward_to_comiitee: "Forward to Committee",
  second_forward: "Second Forward",
  third_forward: "Third Forward",
  new: "New",
  revert_to_applicant: "Revert to Applicant",
  revert_to_checker: "Revert to Checker",
  revert: "Revert",
  forward_to_association: "Forward to Association",
  forward_to_cf_section: "Forward to CF Section",
  selected: "Selected",
  meeting_created: "Meeting Created"
};


export const WORKFORCE_USER_TYPE = {
  ADMIN: "admin",
  CHECKER: "checker",
  APPROVER: "approver",
  APPLICANT: "applicant",
  FACTORY_ADMIN: "factory_admin",
  DIRECTOR: "director",
  ASSOCIATION: "association",
  SECTION_ADMIN: "section_admin",
};
export const WORKFORCE_USER_TYPE_MAP_EN= {
  admin: "Admin",
  checker: "Checker",
  approver: "Approver",
  applicant: "Applicant",
  factory_admin: "Factory Admin",
  director: "Director",
  association: "Association",
  section_admin: "Section Admin",
};
export const WORKFORCE_USER_TYPE_MAP_BN = {
  admin: "অ্যাডমিন",
  checker: "চেকার",
  approver: "অনুমোদনকারী",
  applicant: "আবেদনকারী",
  factory_admin: "ফ্যাক্টরি অ্যাডমিন",
  director: "পরিচালক",
  association: "অ্যাসোসিয়েশন",
  section_admin: "সেকশন অ্যাডমিন",

};